### ISSUE TITLE
Only include realistic hands

### ISSUE THREAD

**Issue by devonfae** [yf-dev/mahjong-hand-guessing-game#14]
After a yakuless hand (number 8, 123m44456678p11s 4p) and one where the player apparently ron'd on a pair of south during south round (number 12, 223344m456789s2z 2z), I came wondering how these hands were being generated. It seems like hands are being randomly generated and then tested for containing yaku. Whatever algorithm you're using allowed the hand in number 8, so I'm not sure how it works. (That hand could only have menzen tsumo or haitei, both conditional yaku for which we don't have the necessary information to assume). Neither hand "feels" like a real mahjong hand, nor do many of the other randomly generated hands so far.

It would make more sense as a guessing game if the hand was realistic, which could mean taken from actual games, or at the very least guaranteed a minimum value, such as only allowing for mangan or higher scoring hands. As it is, the "reward" for discovering the correct answer is not very high. The answer to a guessing game should make sense and seem obvious in hindsight, which only including high value hands would do. Displaying the yaku and point value after a success (or failure) would also assist with this.

Could be done by changing the condition to include a randomly generated hand from "1 or more yaku" to "at least one yaku with a hand score of 3 han 70+ fu / 4 han 40+ fu / 5+ han"

**Comment by devonfae** [comment]
[This blog post](https://pathofhouou.blogspot.com/2021/04/guide-replay-analysis.html) provides five years worth of replays from Tenhou.net's Houou room (the highest rank room), as well as scripts and tools to analyse the data.  We could, for example, extract all winning hands from all 4 player hanchan games played from 2016 through 2020, and use those as the hands for the guessing game. This data includes an enumeration of the hand's yaku, which could be displayed to the user upon win/loss along with the hand itself (as requested in issue #6).

**Comment by Assistant** [comment]
Personally I think the biggest issue is having yaku that can't be deduced from the information given, like menzen tsumo, haitei, or riichi. That can be fixed by limiting the valid yaku even with randomly generated hands, and I think that has some pros like being more accessible to players that are only familiar with the rules of the game and don't know what more realistic hands would look like. It could be argued that players that are better at mahjong should have an advantage, so I believe that's a matter of personal opinion, but having hands with only yaku that can't be deduces seems objectively bad for the enjoyment of the game to me.

**Comment by rishubil** [comment]
In fact, riichi and haitei are not included in the correct answer yaku. However, menzen tsumo is currently included in the correct answer yaku, so there is a problem as you said.
I want to solve this problem as soon as possible, but I really don't have enough time to spend on side projects due to other tasks 😥

**Comment by rishubil** [comment]
changed the answer based on active game logs at 89be55a
